---
abstract: 'Add Perl to your network devices'' command line interfaces'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-REPL-Plugin-NAS
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Devel::REPL: 0
  Net::Appliance::Session: 1.23
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0701
